// Build script: produces ESM, CJS, and IIFE (browser global) builds, each
// in a normal and minified variant, from the single ESM source of truth in
// src/zelvior.js. Run: `node build.mjs`.
//
// MAINTAINERS ONLY. If you just want to *use* zelvior-runtime, you do not
// need to run this — dist/ is already committed and published with every
// npm release. This script requires Node >=18 (esbuild's requirement, not
// the runtime's — the runtime itself targets browsers, not Node, and the
// published dist/ files run in any browser regardless of what Node version
// built them).
//
// Wrapped in an async main() rather than using top-level await so the file
// still *parses* (and fails with a clear message instead of a cryptic
// "Unexpected reserved word" syntax error) on Node <14.8, which lacks
// ESM top-level await.
import { mkdirSync, writeFileSync, readFileSync, copyFileSync } from 'fs';
import { gzipSync } from 'zlib';

async function main() {
  const nodeMajor = parseInt(process.versions.node.split('.')[0], 10);
  if (nodeMajor < 18) {
    console.error(
      `\n[build] This build script requires Node 18+ (esbuild's requirement).\n` +
      `        You are running Node ${process.versions.node}.\n\n` +
      `        You almost certainly do NOT need to run this script at all:\n` +
      `        dist/ ships prebuilt in the npm package and in this tarball.\n` +
      `        Just "npm install zelvior-runtime" and import/require/<script>\n` +
      `        the files already in dist/ — see README.md.\n\n` +
      `        If you really do need to rebuild (e.g. you edited src/zelvior.js),\n` +
      `        use Node 18+ (nvm/volta/fnm can install it alongside any other\n` +
      `        Node version) and re-run "npm run build".\n`
    );
    process.exit(1);
  }

  const { build } = await import('esbuild');

  mkdirSync('dist', { recursive: true });
  copyFileSync('src/zelvior.d.ts', 'dist/zelvior.d.ts');
  for (const name of ['events', 'dom', 'scroll', 'virtual', 'net']) {
    copyFileSync(`src/modules/${name}.d.ts`, `dist/${name}.d.ts`);
  }

  const entry = 'src/zelvior.js';
  const banner = { js: '// Zelvior Runtime — MIT — https://github.com/zelvior/zelvior-runtime' };
  // esbuild's iife globalName exposes the module's *namespace* object
  // ({ default, Scheduler, Observer, ... }). Plain <script> consumers expect
  // Zelvior.enable() directly, so we flatten the namespace onto the default
  // export after the IIFE runs.
  const iifeFooter = { js: 'Object.assign(Zelvior.default,{Scheduler:Zelvior.Scheduler,Observer:Zelvior.Observer,Optimizer:Zelvior.Optimizer,Adaptive:Zelvior.Adaptive,Recycler:Zelvior.Recycler,Memory:Zelvior.Memory,Metrics:Zelvior.Metrics,Plugins:Zelvior.Plugins});Zelvior=Zelvior.default;' };

  const targets = [
    { format: 'esm', outfile: 'dist/zelvior.esm.js', minify: false },
    { format: 'esm', outfile: 'dist/zelvior.esm.min.js', minify: true },
    { format: 'cjs', outfile: 'dist/zelvior.cjs', minify: false },
    { format: 'cjs', outfile: 'dist/zelvior.min.cjs', minify: true },
    { format: 'iife', outfile: 'dist/zelvior.js', minify: false, globalName: 'Zelvior', footer: iifeFooter },
    { format: 'iife', outfile: 'dist/zelvior.min.js', minify: true, globalName: 'Zelvior', footer: iifeFooter },
  ];

  // Standalone, tree-shakeable submodules (src/modules/*.js). Each is fully
  // independent of core zelvior.js and of each other's bundle output (they
  // may *import* one another at the source level -- e.g. scroll.js imports
  // events.js -- but esbuild inlines that at build time, so consumers of
  // just "zelvior-runtime/scroll" never pull in a separate events.js file
  // or the core runtime). ESM + CJS only: these are for bundler/import
  // consumers who want tree-shaking; script-tag/CDN users already have the
  // full Zelvior global from the targets above.
  const moduleNames = ['events', 'dom', 'scroll', 'virtual', 'net'];
  for (const name of moduleNames) {
    const modEntry = `src/modules/${name}.js`;
    targets.push(
      { format: 'esm', outfile: `dist/${name}.esm.js`, minify: false, entry: modEntry },
      { format: 'esm', outfile: `dist/${name}.esm.min.js`, minify: true, entry: modEntry },
      { format: 'cjs', outfile: `dist/${name}.cjs`, minify: false, entry: modEntry },
      { format: 'cjs', outfile: `dist/${name}.min.cjs`, minify: true, entry: modEntry },
    );
  }

  for (const t of targets) {
    await build({
      entryPoints: [t.entry || entry],
      bundle: true,
      format: t.format,
      outfile: t.outfile,
      minify: t.minify,
      sourcemap: t.minify,
      globalName: t.globalName,
      banner,
      footer: t.footer,
      target: ['es2017'],
      legalComments: 'none',
    });
  }

  console.log('\nBundle sizes:');
  let report = '# Bundle Size Report (auto-generated by build.mjs)\n\n| File | Bytes | Gzip Bytes |\n|---|---|---|\n';
  for (const t of targets) {
    const buf = readFileSync(t.outfile);
    const gz = gzipSync(buf, { level: 9 }).length;
    console.log(`${t.outfile.padEnd(28)} ${String(buf.length).padStart(7)} bytes   ${String(gz).padStart(6)} gzip`);
    report += `| ${t.outfile} | ${buf.length} | ${gz} |\n`;
  }
  writeFileSync('BUNDLE_SIZES.md', report);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
